Model Seederの追加
shiyunya/remotatsu pull request #2
Opened 2021-08-18 09:21 UTC by shiyunya

2021-08-18 10:51 UTC, Kai180621 requested changes
- 以下3点
- 他のSeederもUserVoteSeederのように、EloquentのRelationをうまく活用して変更してほしい！

焦らずで大丈夫なので頑張っ！

2021-08-18 10:51 UTC, foolishell commented on app/Models/Difficulty.php
> +    }
`hasMany()`の場合はメソッド名を`tasks`など複数形にする方が良いです！配列(に近いもの)が返ってくるので！

2021-08-18 10:51 UTC, foolishell commented on app/Models/Difficulty.php
> +    }
他のModelも合わせて編集plz

2021-08-18 10:51 UTC, Kai180621 commented on database/migrations/2021_08_18_034733_create_tasks_table.php
> +            $table->text("discription");
typo: description

2021-08-19 01:07 UTC, shiyunya commented
@Kai180621 
ありがとうございます！修正しました。

checksテーブルはわかりにくいので名前をachievementsテーブルに変更しました。
EloquentのRelationはachievementのSeederで苦し紛れに使ってみました。

2021-08-19 01:40 UTC, yumemi-makiyama reviewed
[Comment] 
**Good**
Modelの `fillable` に必要なプロパティが定義されており、Seederは ModelのRelationを上手くつかっている。

**Next(これからは気をつけて欲しい事)**

PRの主旨が 「Model Seederの追加」なのに実装がないControllerがコミットされているのは、PRの単位が適切ではない。これからはPRを分けて欲しい。最低限としてコミットを分けたい。

コミット単位を改善する考え方として、コンパイルエラーにならず正常に実行できる範囲で区切ることがあります。例として考えられるものは下のものです。
- Seederを単位にして、Seederに必要なModelとFactoryを1つのコミットにする。
- Modelだけを全部作ってしまい、Seederとそれに必要なFactoryをSeederごとにコミットする。

2021-08-19 01:43 UTC, merged